apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-microservice
spec:
  selector:
    matchLabels:
      app: restaurant-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: restaurant-microservice
    spec:
      containers:
      - name: restaurant-microservice
        image: manjorno.azurecr.io/restaurant-microservice
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_URL
          value: "http://52.142.38.205/auth"
        - name: KEYCLOAK_USERNAME
          value: backendapp
        - name: KEYCLOAK_PASSWORD
          value: i5JtyQIWfldiwZFuK64w5emej5zGjpde
        - name : KEYCLOAK_CLIENTCLI_SECRET
          value: wINGuKIh73lKM8akMkKrT6n7D65fVm0I
        - name: MONGODB_CONNECTION_URL
          value: mongodb+srv://manjorno-rest:aRW2co3JhKYLCW3S@cluster0.s7ds3.mongodb.net/test?authSource=admin&replicaSet=atlas-egwy6w-shard-0&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=true
        - name: AMQP_CONNECTION_URL
          value: amqp://restaurant-microservice:restaurant123@10.244.0.12:5672
        - name: AMQP_EXCHANGE_USERS
          value: user
        - name: AMQP_EXCHANGE_RESTAURANTS
          value: restaurants
        - name: AMQP_EXCHANGE_EMPLOYEES
          value: employee
        - name: AMQP_EXCHANGE_MENUITEM
          value: menuItem
        ports:
        - containerPort: 3200

---

apiVersion: v1
kind: Service
metadata:
  name: restaurant-microservice
spec:
  selector:
    app: restaurant-microservice
  ports:
  - port: 3200
    targetPort: 3200